apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - parameters.yaml
  - proxy.yaml
  - anthropic-backend.yaml
  - ollama-backend.yaml
  - kagent-ui-route.yaml
  - ash-ph-lab-wildcard-cert.yaml
  - agentgateway-ui-route.yaml
