---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: anthropic-secret
  namespace: agentgateway-system
spec:
  encryptedData:
    Authorization: AgA0HnRNpoZARQFP2BkB8hbkt+lYLIYol83y0t3vPchyeciWvxxxiGl0X68SnV9D6yTyBlJkV5oy2EESsq/uz7nhzJSuZnPXhMD70E9HjpvZQc0hAi2CD/w2oSTsfbuoRYV1NVJbdW3FQV/I0xrEt6gLop9FdOTEQ/kMS9uJ/txp7UsDWURXuqAxzfmPu1/OxbDepNFGKSg8fPEHgf4hsM0Pfdhd8TVvSBw1EfgHXoyOPITTqWY7vHO9OtPTK/b/5WU4Yaw2ylVkYCfA0gPg6Z7VMUxgKK+DmTUQ5qAEXlTATC1NxiuMJ+jXfOp5sd5WEZPFUfexckngVqKRLnUvxEBdRQxxyaFXoXon4W0ayrkN+8DWPmB1oihk0mXTMxbZZvYMv+W9+n8dKKGuK1fflHNAijex84r83xWlz85L4UjrGAgr90WbeFY5dzy0r733NgkIrxbcRhaEq4mPnwGwB7VEWbBiIx0jM3QnVDUsWruT4BHInhqxPiahBj8QGgLsDfrfaGpKJbgl7QU+B7e6MSDUQ53UNIwJrZixH/Dj5kr5nMA1g/tffHXTj65kcxKCrLNYI2a8Pvmf7bHCOBTERynv6Nt6kdJsSP0e/q4AvxbJ8cNHkNbduNtFJSXedxMqkDI/VxG4gv6iwqMj4wXDvRdkII1tlMJqYVjI5DZFlCzQy/nyQ4X1V1NSGAwAe0YrFz8CLQqIHSnYVvMXmSiJecj0YU7zp6jhHmXhWt5JmiFRpby3+unJGdtF/tTCfKrkT4aXMqghIYn1cqAxt4udh3E6ObYWrDitLH4ZDthrsbOnqkxWwRVvMqmjlT2oEyBnsejmMoygLwDtcmuL88U=
  template:
    metadata:
      name: anthropic-secret
      namespace: agentgateway-system
