---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: anthropic-secret
  namespace: agentgateway-system
spec:
  encryptedData:
    Authorization: AgB3ACkXKnLOkTjEZYIMSYvgBKPOVQz8D4v13rT88K2pAIN1F6pj+hB+5aJMAtCHaP7H1OrpzzIWXoiaNr+/5L1nnFG0Kdmi7pwFaV//0GKFaDA0e+pIOK5nrZFD+zE+WQgd6dsDPetXSvy4qiosuBGi9NRUqqACyU2wPSTCoWXOIvrf6E4pvH5V+WROrtg3Hq1eXT6mW52CYnUENwg8vkXZzCwDW/jHGc6Ehyz4eBvIYTe8D+pcv+Sht7oDqmFocWgA4Ppsl/spuXnB8tG3W7XcdYkF+SuTIqMPzwLbv6rBEGXKa9YqXqmTNTBHU26STcbYve84M/z5WNlg6UUvHT8s2pBkmd+xZWVDgjQC8Yc/DCPdcSF/PMc9S1ets0PdEFdlEg4L99MQrwGM0xqYAVzjA/bg/WBY9oe+W9hlAvhP6OUOgfM25iHnJlJRPxwUJf0TOJlIrZ+Nt3CeuIo8BTi7b5eewHA3dMuPm4iOk0fW4t7POaQy0z6zaVojzzE33y7J3e3oRq1pu3PnrgeGMVCVb7LMKY1lKpsC3DBWw26KX5Z1Pojsv7LTG5IrWr2ixjfk4xjvqKZ4qW+xhUGQKTfIE7VoihdhprkTjkTjEGDnPrFEv7GObIEHlIhOl4+4FvP8zXJHlMrjWTBHzVA5cPAj6YrjMjqyFsIfdMaJ6ajgKAq1+gSGE2wKTgK+eKhPg//n7tt+6tbCdux3Z9q8hWc1HH6AHyU2suVh6rPTzzbys8UhPZ8L8OdcVIi9UI/MhmiQEn2FKsfJzVwhzAgGmvTXOqBO97uXO9KEItRE24fgnGXCrAqlR2jVRh+o0wrqlsgympn/ZY1Kv5XrxJ4=
  template:
    metadata:
      name: anthropic-secret
      namespace: agentgateway-system
