---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: anthropic-secret
  namespace: agentgateway-system
spec:
  encryptedData:
    Authorization: AgBiDnpfSMyejcoGXl4R2VMAw7gyA3xQ+WQTF82gCDbFxPqBvWyFCSWFJKGHRPBHTR1da/qsW1tdKbRzMbM8QN0iU3CEt2y39zj1I3BncR1Z108Z5rLJPcS6sqGcthFRkwsbFRP6lOZmGzICTaVcjk7cf+V87liu42xC4gKn5ogfFjitUkwYBohlK36zU2cEpBxVUZTQmFtzXh3bVEWpEbfTA2njN6npw7b5yvRnbWM8wansz+71Zwqf2/IFk1EjkLZNVGpEze5UtienRCjyzd/JJb/exKdBnTGVx7AQjM9G5ffrSOHCcB6OAvpSCQfqP9YFztNUsfOPj/Atmi+vS4dKmZz3YXY2rhoef7d/TQDgwFKj+QKJ3wlnUt4c2McycNjgIqMouTwezqA3IhVEqdIXe1cBUsGRutcx6dZEaaNvUXsbfE1eyjnhfmOclsaCaj9x3TK0sTfN/672f4RC0OX5Ph2GclzDJbYgWN+VzF+5EpiBs9GBmrHIelO26sgC6/32K+fPCLqYoOLHtlCYdIwFY/Xs3Ys+CUNJZhLjZ0HhJCXwMsN6fPOfnFOuLG2vYnUe1wgaDp+AXN36SgvQ3M0AOCd/3Ku8gOlvNIeOeLv8Zi2QEnDG6c1Q1DWfwlXYz1FO28ZJL8FiqeossDHExm5AqndEzf666oC5+9CwMgyGTyX+hY0d7UdGgbdsT2SfUlUqHLE3HVIyjcB/0ghCWPcCl4PksWPrizMEI0emwx0eMZTZ2wJfMMTaeTIyqPgSYPYE6hiBLR4JVssHzhzxWui7LfBFRlp25s9nyRlNv/xshBs3v3PdpZwW4Lb1A6sp/ZhQAKNRt35TWzl76V4=
  template:
    metadata:
      name: anthropic-secret
      namespace: agentgateway-system
