---
apiVersion: v1
kind: Namespace
metadata:
  name: kagent
---
apiVersion: v1
kind: Namespace
metadata:
  name: headlamp
---
apiVersion: v1
kind: Namespace
metadata:
  name: qdrant
---
apiVersion: v1
kind: Namespace
metadata:
  name: doc-writer
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingest-orchestrator
